Table casbin_rule {
  id bigint [pk, increment]
  ptype varchar(100) [not null, default: ``]
  v0 varchar(100) [not null, default: ``]
  v1 varchar(100) [not null, default: ``]
  v2 varchar(100) [not null, default: ``]
  v3 varchar(100) [not null, default: ``]
  v4 varchar(100) [not null, default: ``]
  v5 varchar(100) [not null, default: ``]
  v6 varchar(25) [not null, default: ``]
  v7 varchar(25) [not null, default: ``]

  Indexes {
    (ptype, v0, v1, v2, v3, v4, v5, v6, v7) [unique, name: 'idx_casbin_rules']
  }
}