Table cities {
  id bigint [pk, increment]
  name varchar(255)
  code varchar(255) [not null, unique]
  created_at datetime [not null, default: `CURRENT_TIMESTAMP`]
  updated_at datetime [not null, default: `CURRENT_TIMESTAMP`]
}

Table districts {
  id bigint [pk, increment]
  code varchar(255) [not null, unique]
  name varchar(255)
  city_id bigint [ref: > cities.id, not null]
  my_city_id bigint [ref: > cities.id, not null]
  created_at datetime [not null, default: `CURRENT_TIMESTAMP`]
  updated_at datetime [not null, default: `CURRENT_TIMESTAMP`]

  Indexes {
    city_id [name: 'idx_districts_city_id']
  }
}
