Enum users_status_enum {
  ACTIVE
  DISABLED
  DELETED
}

Table categories {
  id bigint [pk, increment]
  created_at datetime [default: `CURRENT_TIMESTAMP`]
  updated_at datetime [default: `CURRENT_TIMESTAMP`]
  misa_id varchar(100)
  name varchar(50) [not null]
  code varchar(50) [not null]
  level int [not null]
  parent_id bigint  [not null]
  parent_misa_id varchar(100)

Indexes {
  misa_id [unique]
  parent_id [name: 'idx_categories_parent_id']
}
}

Table departments {
  id bigint [pk, increment]
  code varchar(255) [not null]
  name varchar(255) [not null]
  description varchar(255)  [not null]
  created_at datetime [not null, default: `CURRENT_TIMESTAMP`]
  updated_at datetime [not null, default: `CURRENT_TIMESTAMP`]

Indexes {
  code [unique]
  created_at [name: 'created_at']
  updated_at [name: 'updated_at']
}
}

Table product_stocks {
  id bigint [pk, increment]
  created_at datetime [default: `CURRENT_TIMESTAMP`]
  updated_at datetime [default: `CURRENT_TIMESTAMP`]
  misa_product_id varchar(100) [not null]
  misa_stock_id varchar(100) [not null]
  quantity float [default: 0]
  is_default bool [not null, default: 0]

Indexes {
  (misa_product_id, misa_stock_id) [unique, name: 'idx_prd_stk']
}
}

Table products {
  id bigint [pk, increment]
  created_at datetime [default: `CURRENT_TIMESTAMP`]
  updated_at datetime [default: `CURRENT_TIMESTAMP`]
  misa_id varchar(100)
  type varchar(50) [not null]
  uom_id bigint
  misa_uom_id varchar(100)
  is_active bool [not null, default: 1]
  name varchar(255) [not null]
  code varchar(100) [not null]

Indexes {
  misa_id [unique]
  uom_id [name: 'idx_products_uom_id']
}
}

Table request_logs {
  id bigint [pk, increment]
  created_at datetime [default: `CURRENT_TIMESTAMP`]
  updated_at datetime [default: `CURRENT_TIMESTAMP`]
  type varchar(10) [not null, default: 'IN']
  method varchar(10) [not null]
  status varchar(10) [not null]
  path varchar(255) [not null]
  params json
  headers json
  body json
  response json
  user_id varchar(10)
  elapsed_time int
}

Table schema_migrations {
  version bigint [pk, not null]
  dirty bool [not null]
}

Table stocks {
  id bigint [pk, increment]
  created_at datetime [default: `CURRENT_TIMESTAMP`]
  updated_at datetime [default: `CURRENT_TIMESTAMP`]
  misa_id varchar(100)
  name varchar(255) [not null]
  code varchar(50) [not null]
  is_active bool [not null, default: 1]
  branch_id varchar(100)

Indexes {
  misa_id [unique]
}
}

Table uoms {
  id bigint [pk, increment]
  created_at datetime [default: `CURRENT_TIMESTAMP`]
  updated_at datetime [default: `CURRENT_TIMESTAMP`]
  misa_id varchar(100)
  name varchar(50) [not null]
  code varchar(50) [not null]
  operator varchar(50) [not null]
  rate float [not null, default: 1]

Indexes {
  misa_id [unique]
}
}

Table users {
  id bigint [pk, increment]
  full_name varchar(255) [not null]
  email varchar(255) [not null]
  hashed_password varchar(255) [not null]
  telephone varchar(255) [not null]
  address varchar(255)  [not null]
  status users_status_enum [not null]
  department_id bigint [not null]
  token_valid_from datetime
  created_at datetime [not null, default: `CURRENT_TIMESTAMP`]
  updated_at datetime [not null, default: `CURRENT_TIMESTAMP`]

Indexes {
  email [unique]
  created_at [name: 'created_at']
  department_id [name: 'department_id']
  updated_at [name: 'updated_at']
}
}

Table warehouses {
  id bigint [pk, increment]
  code varchar(255) [not null]
  name varchar(255)
  created_at datetime [not null, default: `CURRENT_TIMESTAMP`]
  updated_at datetime [not null, default: `CURRENT_TIMESTAMP`]

Indexes {
  code [unique]
}
}

Table user_warehouse {
  user_id bigint [not null]
  warehouse_id bigint [not null]
  created_at datetime [not null, default: `CURRENT_TIMESTAMP`]
  updated_at datetime [not null, default: `CURRENT_TIMESTAMP`]

Indexes {
  (user_id, warehouse_id) [pk]
  warehouse_id [name: 'warehouse_id']
}
}

Ref:departments.id < users.department_id

Ref:users.id < user_warehouse.user_id

Ref:warehouses.id < user_warehouse.warehouse_id
